version: "3.0"

volumes:
  jc_mysqldata:
  jc_esdata:

services:

  # https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  # https://github.com/k-int/KBPlusG3/blob/dev-integration/SETUP-ES-DOCKER.txt
  # see https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  # see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  jc_es6:
    container_name: jc_es6
    # image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    restart: 'no'
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.name=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200 
      - 9300:9300
    volumes:
      - jc_esdata:/usr/share/elasticsearch/data
    networks:
      default:
        aliases:
          - eshost
          - elasticsearch

  # Connect with mysql --protocol=tcp -h localhost -u k-int -p kbplus700dev
  jc_mysql:
    container_name: jc_mysql
    image: mariadb:10
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: jc
    volumes:
      - jc_mysqldata:/var/lib/mysql
      - ./mysqlinit:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
